---
- hosts: all
  become: true
  pre_tasks:
    - name: update repo index (CentOS)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: update repository index (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"


# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "./vars/vars.yml"

  vars:
    cloudwatch_region: us-west-2
    cloudwatch_deployment: ec2

# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    PLAYBOOK_DIR: "{{ playbook_dir }}"


# ////////////////////////////////////////////////////////////////////////////////////////
#  ROLES
# ////////////////////////////////////////////////////////////////////////////////////////

# EC2 ---------------------------------
- hosts: all
  become: true
  roles:
    - ec2
  when: cloudwatch_deployment == "ec2"

# K8s ---------------------------------
- hosts: all
  become: true
  roles:
    - k8s
  when: cloudwatch_deployment == "k8s"