---
- hosts: all
  become: true
  pre_tasks:
    - name: example pre-task
      shell:
      args:
        executable: /usr/bin/bash
        cmd: echo "Running Playbook..."


# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "./vars/vars.yml"

  vars:
    cloudwatch_region: us-west-2
    deployment_type: ec2


# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    PLAYBOOK_DIR: "{{ playbook_dir }}"


# ////////////////////////////////////////////////////////////////////////////////////////
#  ROLES
# ////////////////////////////////////////////////////////////////////////////////////////

# EC2 ---------------------------------
- hosts: all
  become: true
  roles:
    - ec2
  when: deployment_type == "ec2"

# K8s ---------------------------------
- hosts: all
  become: true
  roles:
    - k8s
  when: cloudwatch_deployment == "k8s"